
x-testing_envs: &testing_envs
  APP_DB_HOST: "${APP_NAME}-db-testing"
  TESTING: "true"
  APP_DB_USER: "test"
  APP_DB_PASSWORD: "test"
  APP_DB_NAME: "test"
  APP_ENABLE_EVENTS: false
  APP_ENABLE_SCHEDULER: false

services:
  app:
    image: ${APP_NAME}-app:testing
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: testing-image
      args:
        INSTALL_DEV: "true"
    container_name: "${APP_NAME}-app-testing"
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - ../.env
    environment:
      <<: *testing_envs
#    volumes:
#      - ../src:/app/src
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - testing


  db:
    image: postgres:17
    container_name: "${APP_NAME}-db-testing"
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    expose:
      - 5432
    tmpfs:
      - /var/lib/postgresql/data
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s
    networks:
      - testing

  nats:
    image: nats:alpine
    container_name: "${APP_NAME}-nats-testing"
    command: ["nats-server", "--cluster", "nats://0.0.0.0:6222", "--http_port", "8222"]
    expose:
      - 4222
      - 6222
      - 8222
    ports:
      - "${APP_NATS_PORT:-4222}:4222"
      - "${APP_NATS_MONITORING_PORT:-8222}:8222"
    restart: "no"
    networks:
      - testing


  redis:
    image: redis:7-alpine
    container_name: "${APP_NAME}-redis"
    restart: always
    expose:
      - 6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 2s
    networks:
      - testing


networks:
  testing: